feat: husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,6 @@
-npx lint-staged
+#!/bin/bash
+
+echo "🏗️👷 Running static checks before committing"
+npx lint-staged || (echo "❌ Failed static checks. Make the changes required above." && exit 1)
+echo "✅ Code passes static checks, committing to local."
+
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,2 +1,5 @@
-npm run build
+#!/bin/bash
 
+echo "🏗️ Checking whether project builds"
+npm run build || (echo "❌ Next build failed: View the errors above to see why." && exit 1)
+echo "✅ Code builds and no issues found, pushing to remote."
